version: "3.5"

services:
  regnskapsregister:
    image: brreg/regnskapsregister-api:latest
    depends_on:
      - postgres
    restart: always
    environment:
      - RRAPI_POSTGRES_DB_URL
      - RRAPI_POSTGRES_DBO_USER
      - RRAPI_POSTGRES_DBO_PASSWORD
      - RRAPI_POSTGRES_USER
      - RRAPI_POSTGRES_PASSWORD
      - RRAPI_SFTP_SERVER
      - RRAPI_SFTP_USER
      - RRAPI_SFTP_PASSWORD
      - RRAPI_SFTP_PORT
      - RRAPI_SFTP_DIRECTORY
      - RRAPI_SLACK_TOKEN
      - RRAPI_IP_SALT
    ports:
      - 8080:8080

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$RRAPI_POSTGRES_DBO_USER
      - POSTGRES_PASSWORD=$RRAPI_POSTGRES_DBO_PASSWORD
    volumes:
      - /var/lib/postgresql/data
